### ISSUE TITLE
Aeotec Smart Switch 6 not registering power consumption

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/zwave-adapter#5]
Originally from: https://github.com/mozilla-iot/gateway/issues/543

I have the UK version of the Aeotec Smart Switch 6 and it always shows in the UI as 0W of power consumption (model ZW096-C07).

![screenshot](https://user-images.githubusercontent.com/552417/35455263-27da5458-02c9-11e8-954f-d8662c8b8922.png)

**Comment by dhylands** [comment]
It would be good to get the OZW_Log.txt and the console log from the gateway with one of these devices plugged in.

**Comment by mrstegeman** [comment]
@benfrancis Could you get us some additional logs?

**Comment by twobraids** [comment]
Just to let you know, my newly acquired US version Aeotec Smart Switch 6 works fine: it registers power consumption correctly.

**Comment by mrstegeman** [comment]
@twobraids as do mine and @dhylands'. It seems to just be the UK version for some reason.

**Comment by mrstegeman** [comment]
I wonder if a firmware update might solve this? It appears that the EU/AU/UK version has a different firmware than the US version, but there have been some updates:

https://aeotec.freshdesk.com/support/solutions/articles/6000134294-smart-switch-6-firmware-update-3-26-2018-

**Comment by benfrancis** [comment]
Oh man, requires ZStick and Microsoft Windows...

Will try this if I get a chance, thanks.

**Comment by mrstegeman** [comment]
This should theoretically be fixed now, as there was a UI bug. Please re-test when you have time.

**Comment by mrstegeman** [comment]
@benfrancis This should theoretically be fixed now, as there was a UI bug. Please re-test when you have time.

**Comment by mrstegeman** [comment]
I'm going to assume this is fixed now. Please re-open if that's not the case.

**Comment by benfrancis** [comment]
Unfortunately still not working.

It always reports `instantaneousPower` as 0.000W

**Comment by dhylands** [comment]
Can you send the ~/.mozilla-iot/config/zb-XXXXXX.cfg file entry for the smart plug?

**Comment by benfrancis** [comment]
> Can you send the ~/.mozilla-iot/config/zb-XXXXXX.cfg file entry for the smart plug?

I can't see any .cfg files in that directory (or anywhere in the /home/pi directory). Is the config somewhere else? Note this a Z-Wave device.

**Comment by dhylands** [comment]
Sorry, wrong extension. It should be .json? The file is found in the config directory (which is typically ~/.mozilla-iot/config) and starts with zb and has an 8-character hex number in the name (which is the serial number of the zigbee dongle)

**Comment by mrstegeman** [comment]
@dhylands Z-Wave, not Zigbee.

**Comment by mrstegeman** [comment]
@benfrancis I'm guessing @dhylands meant to say `~/.mozilla-iot/log/zwcfg_0xXXXXXXXX.xml`. Can you attach that file?
